server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: blogs
          uri: lb://BLOGS #eureka website se liya gya hai, waha listed hoga
          predicates:
            - Path=/api/blogs/**
        - id: products
          uri: lb://PRODUCTS  #eureka website se liya gya hai, waha listed hoga
          predicates:
            - Path=/api/products/**
        - id: users
          uri: lb://USERS  #eureka website se liya gya hai, waha listed hoga
          predicates:
            - Path=/api/users/**
